extract_version:
  provider: 'file'
  file:
    file: 'package.json'
    regex: '"version": "(.+)-dev"'

common: &common
  package_name: pulsar-dev
  ppm_executable: ppm-dev
  before_build_script: .omnipackage/nvm.sh
  maintainer: Oleg Antonyan <oleg.b.antonyan@gmail.com>
  homepage: https://pulsar-edit.dev
  description: A Community-led Hyper-Hackable Text Editor

rpm: &rpm
  <<: *common
  rpm:
    spec_template: .omnipackage/specfile.spec.liquid

deb: &deb
  <<: *common
  build_dependencies: ['libsecret-1-dev', 'libx11-dev', 'libxkbfile-dev', 'build-essential', 'python3-setuptools', 'curl', 'git', 'libxshmfence-dev', 'libnss3-dev', 'libnspr4-dev', 'libatk1.0-dev', 'libatk-bridge2.0-dev', 'libdbus-1-dev', 'libgdk-pixbuf2.0-dev', 'libgtk-3-dev', 'libpango1.0-dev', 'libcairo2-dev', 'libxcomposite-dev', 'libxdamage-dev', 'libxfixes-dev', 'libxrandr-dev', 'libxkbcommon-dev', 'libgbm-dev', 'libasound2-dev', 'libcups2-dev', 'libatspi2.0-dev', 'libssl-dev']
  deb:
    debian_templates: .omnipackage/deb

opensuse: &opensuse
  build_dependencies: ['libsecret-devel', 'libX11-devel', 'libxkbfile-devel', 'gcc', 'gcc-c++', 'make', 'python3-setuptools', 'curl', 'git', 'libopenssl-devel']
  <<: *rpm

redhat: &redhat
  build_dependencies: ['libsecret-devel', 'libX11-devel', 'gcc', 'gcc-c++', 'make', 'curl', 'git', 'openssl-devel']
  <<: *rpm
  before_build_script: .omnipackage/nvm_rhel.sh

fedora: &fedora
  build_dependencies: ['libsecret-devel', 'libX11-devel', 'libxkbfile-devel', 'gcc', 'gcc-c++', 'make', 'python3-setuptools', 'curl', 'git', 'openssl-devel']
  <<: *rpm

mageia: &mageia
  build_dependencies: ['lib64secret-devel', 'lib64x11-devel', 'lib64xkbfile-devel', 'gcc', 'gcc-c++', 'make', 'python3-setuptools', 'curl', 'git', 'lib64openssl-devel']
  <<: *rpm

debian_testing: &debian_testing
  <<: *deb
  build_dependencies: ['libsecret-1-dev', 'libx11-dev', 'libxkbfile-dev', 'build-essential', 'python3-setuptools', 'curl', 'git', 'libxshmfence-dev', 'libnss3-dev', 'libnspr4-dev', 'libatk1.0-dev', 'libatk-bridge2.0-dev', 'libdbus-1-dev', 'libgdk-pixbuf-xlib-2.0-dev', 'libgtk-3-dev', 'libpango1.0-dev', 'libcairo2-dev', 'libxcomposite-dev', 'libxdamage-dev', 'libxfixes-dev', 'libxrandr-dev', 'libxkbcommon-dev', 'libgbm-dev', 'libasound2-dev', 'libcups2-dev', 'libatspi2.0-dev', 'libssl-dev', 'libcurl4-openssl-dev']

builds:
- distro: 'opensuse_tumbleweed'
  <<: *opensuse
- distro: 'opensuse_15.6'
  <<: *opensuse
- distro: 'opensuse_15.5'
  <<: *opensuse
- distro: 'opensuse_15.4'
  <<: *opensuse
- distro: 'opensuse_15.3'
  <<: *opensuse
- distro: 'fedora_38'
  <<: *fedora
- distro: 'fedora_39'
  <<: *fedora
- distro: 'fedora_40'
  <<: *fedora
- distro: 'fedora_41'
  <<: *fedora
#- distro: 'fedora_rawhide'
#  <<: *fedora
- distro: 'ubuntu_20.04'
  <<: *deb
- distro: 'ubuntu_22.04'
  <<: *deb
- distro: 'ubuntu_24.04'
  <<: *deb
- distro: 'debian_10'
  <<: *deb
- distro: 'debian_11'
  <<: *deb
- distro: 'debian_12'
  <<: *deb
- distro: 'debian_testing'
  <<: *debian_testing
- distro: 'debian_unstable'
  <<: *debian_testing
- distro: 'rockylinux_8'
  <<: *redhat
- distro: 'rockylinux_9'
  <<: *redhat
- distro: 'mageia_8'
  <<: *mageia
- distro: 'mageia_9'
  <<: *mageia
#- distro: 'mageia_cauldron'
#  <<: *mageia
